# vim ft=yaml
# travis-ci.org definition for gfusion build
language: python
sudo: false
python:
  - "2.7"
#  - "3.2"
  #- "3.3"
  #- "3.4"
  #- "3.5"
#  - "pypy"
#  - "pypy3"
cache:
  - pip

install:
  - travis_retry pip install -q coveralls codecov
  - pip install -r requirements.txt
  # - pip install -e '.[tests]'

script:
  - nosetests --with-doctest --with-coverage --cover-package gfusion --logging-level=INFO -v

after_success:
  - coveralls
  - codecov
